
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysmon.h"

/*
* The configuration table for devices
*/

XSysMon_Config XSysMon_ConfigTable[] =
{
	{
		XPAR_XADC_WIZ_0_DEVICE_ID,
		XPAR_XADC_WIZ_0_BASEADDR,
		XPAR_XADC_WIZ_0_INCLUDE_INTR
	}
};


