# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0

add_files D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_OOC.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/bd/system/system.bd]

read_verilog {
  D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/imports/Desktop/PWM_Controller.v
  D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.srcs/sources_1/imports/hdl/system_wrapper.v
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution/xadc_led_first_solution.data/wt [current_project]
set_property parent.project_dir D:/PFE-Install/Vivado/2013.4/my_job/xadc_led_first_solution [current_project]
synth_design -top system_wrapper -part xc7z020clg484-1
write_checkpoint system_wrapper.dcp
report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb
